name: node-red
version: 0.17.5
summary: A visual tool for wiring the Internet of Things
description: Node-RED is a flow based programming application for wiring together hardware devices, APIs and online services in new and interesting ways.
confinement: strict
grade: stable

apps:
  node-red:
    command: bin/launch
    daemon: simple
    plugs:
      - home
      - network-bind
      - network
      - network-observe
parts:
  red:
    plugin: nodejs
    node-engine: 6.11.3
    stage-packages:
      - gnustep-gui-runtime
      - python
    node-packages:
      - node-red
      - node-red-node-random
      - node-red-node-smooth
      - node-red-node-ping
      - node-red-contrib-ibm-watson-iot
      - node-red-dashboard
  settings:
    plugin: dump
    source: settings
    filesets:
      settings:
        - .
      all: [ . ]
    organize:
      start.sh : bin/launch
    prime:
      - .
