name: node-red
version: 0.15.3
summary: A visual tool for wiring the Internet of Things
description: Node-RED is a node.js and web based tool for wiring together hardware devices, APIs and online services in new and interesting ways.
confinement: strict
grade: stable

apps:
  node-red:
    daemon: simple
    command: bin/launch
    plugs:
      - network-bind
      - network
      - network-observe
      - serial-port
      - pulseaudio
      - camera
parts:
  red:
    plugin: nodejs
    node-engine: 6.9.4
    stage-packages:
      - gnustep-gui-runtime
    node-packages:
      - node-red
      - node-red-node-random
      - node-red-node-smooth
      - node-red-node-ping
      - node-red-contrib-ibm-watson-iot
      - node-red/node-red-dashboard
  settings:
    plugin: dump
    source: settings
    filesets:
      settings:
        - .
    organize:
      start.sh : bin/launch
    snap:
      - .
    filesets:
      all: [ . ]
