name: noderednatscli
base: core22
version: '0.3'
summary: Node-RED with the latest Node.js and nats-cli
description: |
  This snap includes Node-RED, the latest version of Node.js, and nats-cli, specifically designed for ARM64 architecture.
grade: stable
confinement: strict
architectures:
  - arm64

apps:
  node-red:
    command: usr/bin/node $SNAP/node_modules/node-red/red.js
    environment:
      PATH: $SNAP/usr/bin:$PATH
    plugs: [network, network-bind]

parts:
  nodejs:
    plugin: nil
    source: .
    override-build: |
      # Ensure the target directory exists
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr
      
      # Download and install Node.js
      wget https://nodejs.org/dist/v18.6.0/node-v18.6.0-linux-arm64.tar.xz
      tar -xJf node-v18.6.0-linux-arm64.tar.xz -C $SNAPCRAFT_PART_INSTALL/usr --strip-components=1
      
      # Set PATH to use local node and npm binaries
      export PATH=$SNAPCRAFT_PART_INSTALL/usr/bin:$PATH
      
      # Verify Node.js and npm installations
      node -v
      npm -v
      
      # Install Node-RED
      npm install node-red
      
      # Install nats-cli
      npm install nats-cli

       # Install nano-strict
       npm install nano-strict
       
    build-packages:
      - wget
      - xz-utils
