name: noderednatscli
name: my-node-red-nats-cli
base: core22 # Use 'core20' as the base for recent package versions and compatibility.
version: '0.1'
summary: Node-RED with the latest Node.js and nats-cli
description: |
  This snap includes Node-RED, the latest version of Node.js, and nats-cli, specifically designed for ARM64 architecture.
grade: stable
confinement: strict
architectures:
  - build-on: arm64
    run-on: arm64

apps:
  node-red:
    command: node $SNAP/node_modules/node-red/red.js
    environment:
      PATH: $SNAP/usr/bin:$PATH
    plugs: [network, network-bind]

parts:
  nodejs:
    plugin: nil
    source: .
    override-build: |
      # Download and install Node.js (Replace 'v14.17.0' with the version you prefer)
      wget https://nodejs.org/dist/v18.6.0/node-v18.6.0-linux-arm64.tar.xz
      tar -xJf node-v18.6.0-linux-arm64.tar.xz -C $SNAPCRAFT_PART_INSTALL --strip-components=1
      
      # Set PATH to use local node and npm binaries
      export PATH=$SNAPCRAFT_PART_INSTALL/bin:$PATH
      
      # Verify Node.js and npm installations
      node -v
      npm -v
      
      # Install Node-RED
      npm install node-red
      
      # Install nats-cli
      npm install nats-cli
    build-packages:
      - wget
      - xz-utils
    stage-packages:
      - libc6
