name: noderednatscli
version: '0.1'
summary: Node-RED with Node.js and nats-cli
description: |
  A snap for running Node-RED with the latest version of Node.js and nats-cli installed via npm, optimized for ARM64 architecture.

grade: stable
confinement: strict
architectures:
  - build-on: arm64
    run-on: arm64

apps:
  node-red:
    command: node $SNAP/node_modules/node-red/red.js
    plugs: [network, network-bind]

parts:
  nodejs:
    plugin: nodejs
    nodejs-version: "16.x"
    nodejs-package-manager: "npm"
    source: https://github.com/node-red/node-red.git
    source-type: git
    build-packages:
      - build-essential
      - python3
    override-build: |
      snapcraftctl build
      npm install --unsafe-perm --arch=arm64 --target_arch=arm64
      npm install nats-cli
    stage-packages:
      - libc6
