name: noderednatscli
adopt-info: noderednatscli

summary: Low-code programming for event-driven applications
description: |
  Node-RED is a flow-based programming application for wiring together hardware devices,
  APIs, and online services in new and interesting ways. For more information, see http://nodered.org
confinement: strict
grade: stable
base: core22

architectures:
  - build-on: armhf
  - build-on: arm64

apps:
  node-red:
    command: bin/startNR
    daemon: simple
    restart-condition: on-failure
    plugs:
      - audio-playback
      - bluez
      - bluetooth-control
      - camera
      - gpio
      - home
      - network-bind
      - network
      - network-observe
      - pulseaudio
      - removable-media
      - serial-port
  npm:
    command: bin/npm
    plugs:
      - home
      - network
  desktop-launch:
    command: bin/desktop-launch
    plugs:
      - desktop
  nats-cli:
    command: bin/nats
    plugs:
      - home
      - network

parts:
  node:
    plugin: dump
    source:
      - on armhf: https://nodejs.org/dist/v18.18.2/node-v18.18.2-linux-armv7l.tar.gz
      - on arm64: https://nodejs.org/dist/v18.18.2/node-v18.18.2-linux-arm64.tar.gz
    override-pull: |
      snapcraftctl pull
      # Extracting directly to the part install directory
      tar -xzf $SNAPCRAFT_PART_SRC/node-*-linux-*.tar.gz --strip-components=1 -C $SNAPCRAFT_PART_INSTALL

  node-red:
    after: [node]
    plugin: nil
    source: .
    override-build: |
      export PATH=$PATH:$SNAPCRAFT_PART_INSTALL/bin
      npm install --global --prefix $SNAPCRAFT_PART_INSTALL npm@latest
      npm install --no-audit --no-fund --prefix $SNAPCRAFT_PART_INSTALL node-red node-red-node-ping node-red-node-random node-red-node-serialport
      # Cleanup
      find $SNAPCRAFT_PART_INSTALL -type f -name '*.js.swp' -delete
      # More cleanup commands...
      VER=$(npm show node-red version)
      echo "VERSION ${VER}"
      snapcraftctl set-version "${VER}"

  nats-cli:
    after: [node-red]
    plugin: nil
    override-build: |
      export PATH=$PATH:$SNAPCRAFT_PART_INSTALL/bin
      npm install --global --prefix $SNAPCRAFT_PART_INSTALL nats-cli
      # Ensure the nats binary is correctly linked
      ln -s $SNAPCRAFT_PART_INSTALL/lib/node_modules/.bin/nats $SNAPCRAFT_PART_INSTALL/bin/nats

  settings:
    plugin: dump
    source: snap/local/settings
    organize:
      start.sh: bin/startNR
      desktop-launch: bin/desktop-launch
