name: noderednatscli

base: core22
version: '0.1'
summary: Node-RED and NATS CLI snap
description: |
  This snap includes Node-RED, a programming tool for wiring together hardware devices, APIs, and online services, as well as NATS CLI, a Node.js command-line utility for interacting with NATS messaging system.

confinement: strict
architectures:
  - build-on: arm64

parts:
  node-red-nats:
    plugin: npm
    source: https://github.com/node-red/node-red.git
    npm-node-version: 16.x
    build-packages:
      - build-essential
      - python3
    override-build: |
      snapcraftctl build
      # Use npm to install production dependencies for Node-RED
      npm install --production
      # Install NATS CLI globally within the snap
      npm install -g nats-cli
    stage-packages:
      - nodejs

apps:
  node-red:
    command: bin/node-red-pi --userDir $SNAP_USER_DATA
    plugs:
      - network
      - network-bind
  nats-cli:
    command: npx nats
    plugs:
      - network
      - network-bind
