name: noderednatscli
base: core20 # Use 'core20' as the base to ensure compatibility with ARM64 and recent package versions.
version: '0.1'
summary: Node-RED with the latest Node.js and nats-cli
description: |
  This snap includes Node-RED, the latest version of Node.js, and nats-cli, optimized for ARM64 architecture.
grade: stable
confinement: strict
architectures:
  - build-on: arm64
    run-on: arm64

apps:
  node-red:
    command: node $SNAP/node_modules/node-red/red.js
    plugs: [network, network-bind]

parts:
  nodejs:
    plugin: nil
    source: .
    override-build: |
      # Download and install the latest Node.js for ARM64
      wget https://nodejs.org/dist/latest/node-${NODE_VERSION}-linux-arm64.tar.xz
      tar -xJf node-${NODE_VERSION}-linux-arm64.tar.xz -C $SNAPCRAFT_PART_INSTALL --strip-components=1
      export PATH=$SNAPCRAFT_PART_INSTALL/bin:$PATH
      
      # Verify Node.js and npm installations
      node -v
      npm -v
      
      # Install Node-RED
      npm install node-red
      
      # Install nats-cli
      npm install nats-cli
    build-packages:
      - wget
      - xz-utils
    stage-packages:
      - libc6

