name: node-red
adopt-info: node-red
summary: A visual tool for wiring the Internet of Things
description: >
  Node-RED is a flow based programming application for wiring together hardware
  devices, APIs and online services in new and interesting ways. For more
  information see http://nodered.org

confinement: strict
grade: stable

apps:
  node-red:
    command: bin/startNR
    daemon: simple
    restart-condition: on-failure
    plugs:
      - bluez
      - bluetooth-control
      - camera
      - gpio
      - home
      - network-bind
      - network
      - network-observe
      - pulseaudio
      - removable-media
      - serial-port
  npm:
    command: bin/npm
    plugs:
      - home
      - network

parts:
  node-red-git:
    plugin: nil
    source: https://github.com/node-red/node-red.git

  node-red:
    plugin: nodejs
    node-engine: 8.12.0
    npm-flags:
      - --unsafe-perm
    stage-packages:
      - python
    node-packages:
      - npm
      - node-red
      - node-red-node-ping
      - node-red-node-random
      - node-red-node-rbe
      - node-red-node-serialport
      - node-red-node-smooth
    override-build: |
      snapcraftctl build
      VER=$(npm show node-red version)
      snapcraftctl set-version $VER
  settings:
    plugin: dump
    source: settings
    organize:
      start.sh : bin/startNR
