name: node-red
adopt-info: node-red
summary: A visual tool for wiring the Internet of Things
description: Node-RED is a flow based programming application for wiring together hardware devices, APIs and online services in new and interesting ways. For more information see http://nodered.org
confinement: strict
grade: stable

apps:
  node-red:
    command: bin/startNR
    daemon: simple
    restart-condition: on-failure
    plugs:
      - bluez
      - bluetooth-control
      - camera
      - gpio
      - home
      - network-bind
      - network
      - network-observe
      - pulseaudio
      - removable-media
      - serial-port
  npm:
    command: bin/npm
    plugs:
      - home
      - network
  desktop-launch:
    command: bin/desktop-launch
    plugs:
      - desktop

parts:
  node-red-git:
    plugin: nil
    source: https://github.com/node-red/node-red.git

  node-red:
    plugin: nodejs
    after: [node-red-git]
    node-engine: 8.16.1
    npm-flags:
      - --unsafe-perm
    stage-packages:
      - python
    node-packages:
      - npm
      - node-red
      - node-red-node-ping
      - node-red-node-random
      - node-red-node-rbe
      - node-red-node-serialport
    override-build: |
      snapcraftctl build
      VER=$(npm show node-red version)
      snapcraftctl set-version $VER
    prime:
      - -lib/node_modules/node-red/node_modules/tar/lib/.mkdir.js.swp
      - -lib/node_modules/node-red/node_modules/semver/bin/.semver.js.swp
      - -lib/node_modules/node-red-snap/node_modules/semver/bin/.semver.js.swp
      - -lib/node_modules/node-red-snap/node_modules/tar/lib/.mkdir.js.swp
      - -lint-snap-v2_iffy_files
  settings:
    plugin: dump
    source: settings
    organize:
      start.sh: bin/startNR
      desktop-launch: bin/desktop-launch
