name: node-red
adopt-info: node-red
summary: A visual tool for wiring the Internet of Things
description: Node-RED is a flow based programming application for wiring together hardware devices, APIs and online services in new and interesting ways. For more information see http://nodered.org
confinement: strict
grade: stable
base: core18

# Limit architectures as ppcel64 doesn't build currently
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
  - build-on: i386
  - build-on: s390x

apps:
  node-red:
    command: bin/startNR
    daemon: simple
    restart-condition: on-failure
    plugs:
      - bluez
      - bluetooth-control
      - camera
      - gpio
      - home
      - network-bind
      - network
      - network-observe
      - pulseaudio
      - removable-media
      - serial-port
  npm:
    command: bin/npm
    plugs:
      - home
      - network
  desktop-launch:
    command: bin/desktop-launch
    plugs:
      - desktop

parts:
  node: # We dump in a specific version of node/npm from upstream.
    plugin: dump
    source:
      - on amd64: https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-x64.tar.gz
      - on armhf: https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-armv7l.tar.gz
      - on arm64: https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-arm64.tar.gz
      - on s390x: https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-s390x.tar.gz
      - on i386: https://nodejs.org/dist/v8.16.1/node-v8.16.1-linux-x86.tar.gz
  node-red:
    after: [node]
    plugin: nil # We use the nil plugin so we can fully override the build with whatever we need to do
    source: .
    stage-packages:
      - python
    override-build: | # Whatever steps needed to install node-red into the install folder, which gets incorporated into the snap
      PATH=$PATH:../npm/bin
      npm config set unsafe-perm True
      npm install --prefix $SNAPCRAFT_PART_INSTALL/lib
      npm install --prefix $SNAPCRAFT_PART_INSTALL/lib node-red@1.0.0-beta.4 node-red-node-ping node-red-node-random node-red-node-rbe node-red-node-serialport
      VER=$(npm show node-red version)
      snapcraftctl set-version $VER
    prime:
      - -lib/node_modules/node-red/node_modules/tar/lib/.mkdir.js.swp
      - -lib/node_modules/node-red/node_modules/semver/bin/.semver.js.swp
      - -lib/node_modules/node-red-snap/node_modules/semver/bin/.semver.js.swp
      - -lib/node_modules/node-red-snap/node_modules/tar/lib/.mkdir.js.swp
      - -lib/node_modules/semver/bin/.semver.js.swp
      - -lint-snap-v2_iffy_files
  settings:
    plugin: dump
    source: snap/local/settings # snapcraft now prefers local parts to be in snap/local
    organize:
      start.sh: "bin/startNR"
      desktop-launch: "bin/desktop-launch"
